package com.aexp.yin.y.ming.model;

import java.io.Serializable;

/**
 * Employee definition.
 * 
 * This file was generated by Ignite Web Console (12/12/2017, 14:31)
 **/
public class Employee implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for empName. */
    private String empName;

    /** Value for empSalary. */
    private Double empSalary;

    /**
     * Gets empName
     * 
     * @return Value for empName.
     **/
    public String getEmpName() {
        return empName;
    }

    /**
     * Sets empName
     * 
     * @param empName New value for empName.
     **/
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * Gets empSalary
     * 
     * @return Value for empSalary.
     **/
    public Double getEmpSalary() {
        return empSalary;
    }

    /**
     * Sets empSalary
     * 
     * @param empSalary New value for empSalary.
     **/
    public void setEmpSalary(Double empSalary) {
        this.empSalary = empSalary;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Employee))
            return false;
        
        Employee that = (Employee)o;

        if (empName != null ? !empName.equals(that.empName) : that.empName != null)
            return false;
        

        if (empSalary != null ? !empSalary.equals(that.empSalary) : that.empSalary != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = empName != null ? empName.hashCode() : 0;

        res = 31 * res + (empSalary != null ? empSalary.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Employee [" + 
            "empName=" + empName + ", " + 
            "empSalary=" + empSalary +
        "]";
    }
}