package load;

import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (12/12/2017, 14:31) **/
public class LoadCaches {
    /**
     * <p>
     * Utility to load caches from database.
     * <p>
     * How to use:
     * <ul>
     *     <li>Start cluster.</li>
     *     <li>Start this utility and wait while load complete.</li>
     * </ul>
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        try (Ignite ignite = Ignition.start("MyIgniteCluster-client.xml")) {
            System.out.println(">>> Loading caches...");

            System.out.println(">>> Loading cache: EmployeeCache");
            ignite.cache("EmployeeCache").loadCache(null);

            System.out.println(">>> All caches loaded!");
        }
    }
}